### ISSUE TITLE
[appsody stack - 443] Implement service monitoring support for java-microprofile and add timeoutSeconds for readinessProbe

### ISSUE THREAD

**Issue by nastacio** [nastacio/github-board-sync-test#13]
Aggregated from: https://api.github.com/repos/appsody/stacks/issues/443

Description in source issue:

Following https://github.com/appsody/appsody-operator/pull/125, the Appsody operator supports creating service monitor if there is a `spec.monitoring` entry in the `app-deploy.yaml` file. The only requirement to utilise this is a label field, like so:

```
apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: example-appsodyapplication
spec:
  ....
  monitoring:
    endpoints:
    - basicAuth:
        password:
          key: password
          name: pass
        username:
          key: username
          name: user
      interval: 5s
      tlsConfig:
        insecureSkipVerify: true
    labels:
      k8s-app: APPSODY_PROJECT_NAME
```
We introduced this functionality for Python Flask, Node.js-Express, and Node.js-functions but it would be nice to see this for Java-Microprofile also.

Currently, we also see a Knative error if a stack uses the `readinessProbe` and `timeoutSeconds` is not defined.

**Describe the solution you'd like**
Add a new field (`monitoring`) to the `app-deploy` file underneath `spec`. The java-microprofile stack has authenticated endpoints and therefore requires a `basicAuth` field also.

Also add a new field, `timeoutSeconds` under the `readinessProbe` and assign it an appropriate value e.g. 1.

**Additional context**
Example PR to implement service monitor support into a stack: https://github.com/appsody/stacks/pull/419/files

**Note**: The PR above is for a stack without an authenticated endpoint, see: https://github.com/appsody/appsody-operator/pull/125 for a more suitable approach for microprofile.
